USE Traceability;
GO
-- --- DROP TABLES (Xóa theo thứ tự ngược lại để tránh lỗi FK) ---
IF OBJECT_ID('PRODUCT_HAS_DISCOUNT', 'U') IS NOT NULL DROP TABLE PRODUCT_HAS_DISCOUNT;
IF OBJECT_ID('DISCOUNT', 'U') IS NOT NULL DROP TABLE DISCOUNT;
IF OBJECT_ID('PRICE', 'U') IS NOT NULL DROP TABLE PRICE;
IF OBJECT_ID('SHIP_BATCH', 'U') IS NOT NULL DROP TABLE SHIP_BATCH;
IF OBJECT_ID('STORED_IN', 'U') IS NOT NULL DROP TABLE STORED_IN;
IF OBJECT_ID('PROCESSING', 'U') IS NOT NULL DROP TABLE PROCESSING;
IF OBJECT_ID('BATCH', 'U') IS NOT NULL DROP TABLE BATCH;
IF OBJECT_ID('VENDOR_PRODUCT', 'U') IS NOT NULL DROP TABLE VENDOR_PRODUCT;
IF OBJECT_ID('AGRICULTURE_PRODUCT', 'U') IS NOT NULL DROP TABLE AGRICULTURE_PRODUCT;
IF OBJECT_ID('TRANSPORLEG', 'U') IS NOT NULL DROP TABLE TRANSPORLEG;
IF OBJECT_ID('SHIPMENT', 'U') IS NOT NULL DROP TABLE SHIPMENT;
IF OBJECT_ID('DISTRIBUTOR', 'U') IS NOT NULL DROP TABLE DISTRIBUTOR;
IF OBJECT_ID('RETAIL', 'U') IS NOT NULL DROP TABLE RETAIL;
IF OBJECT_ID('CARRIERCOMPANY', 'U') IS NOT NULL DROP TABLE CARRIERCOMPANY;
IF OBJECT_ID('VENDOR', 'U') IS NOT NULL DROP TABLE VENDOR;
IF OBJECT_ID('PROCESS_STEP', 'U') IS NOT NULL DROP TABLE PROCESS_STEP;
IF OBJECT_ID('PROCESSING_FACILITY', 'U') IS NOT NULL DROP TABLE PROCESSING_FACILITY;
IF OBJECT_ID('FARM_CERTIFICATIONS', 'U') IS NOT NULL DROP TABLE FARM_CERTIFICATIONS;
IF OBJECT_ID('FARM', 'U') IS NOT NULL DROP TABLE FARM;
IF OBJECT_ID('WAREHOUSE', 'U') IS NOT NULL DROP TABLE WAREHOUSE;
IF OBJECT_ID('PROVINCE', 'U') IS NOT NULL DROP TABLE PROVINCE;
IF OBJECT_ID('[TYPE]', 'U') IS NOT NULL DROP TABLE [TYPE];
IF OBJECT_ID('CATEGORY', 'U') IS NOT NULL DROP TABLE CATEGORY;
IF OBJECT_ID('COUNTRY', 'U') IS NOT NULL DROP TABLE COUNTRY;



CREATE TABLE COUNTRY (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE CATEGORY (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE PROVINCE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    C_ID INT NOT NULL,
    FOREIGN KEY (C_ID) REFERENCES COUNTRY(ID),
    UNIQUE(Name, C_ID)
);

CREATE TABLE [TYPE] (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Variety NVARCHAR(100) NOT NULL,
    C_ID INT NOT NULL,
    FOREIGN KEY (C_ID) REFERENCES CATEGORY(ID)
);

CREATE TABLE FARM (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Owner_Name NVARCHAR(255),
    Contact_Info VARCHAR(255),
    Address_detail NVARCHAR(255),
    Longitude DECIMAL(9, 6) NOT NULL CHECK (Longitude BETWEEN -180 AND 180),
    Latitude DECIMAL(9, 6) NOT NULL CHECK (Latitude BETWEEN -90 AND 90),
    P_ID INT NOT NULL,
    FOREIGN KEY (P_ID) REFERENCES PROVINCE(ID)
);

CREATE TABLE FARM_CERTIFICATIONS (
    F_ID INT NOT NULL,
    FarmCertifications NVARCHAR(255) NOT NULL,
    PRIMARY KEY (F_ID, FarmCertifications),
    FOREIGN KEY (F_ID) REFERENCES FARM(ID) ON DELETE CASCADE
);

CREATE TABLE PROCESSING_FACILITY (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Address_detail NVARCHAR(255) NOT NULL,
    Contact_Info VARCHAR(255),
    License_Number VARCHAR(100) NOT NULL UNIQUE,
    Longitude DECIMAL(9, 6) CHECK (Longitude BETWEEN -180 AND 180),
    Latitude DECIMAL(9, 6) CHECK (Latitude BETWEEN -90 AND 90),
    P_ID INT,
    FOREIGN KEY (P_ID) REFERENCES PROVINCE(ID)
);

CREATE TABLE WAREHOUSE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Capacity DECIMAL(10, 2) CHECK (Capacity > 0),
    Store_Condition NVARCHAR(255),
    Address_detail NVARCHAR(255) NOT NULL,
    Longitude DECIMAL(9, 6) CHECK (Longitude BETWEEN -180 AND 180),
    Latitude DECIMAL(9, 6) CHECK (Latitude BETWEEN -90 AND 90),
    P_ID INT NOT NULL,
    FOREIGN KEY (P_ID) REFERENCES PROVINCE(ID)
);

CREATE TABLE AGRICULTURE_PRODUCT (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Image_URL VARCHAR(2048),
    T_ID INT NOT NULL,
    FOREIGN KEY (T_ID) REFERENCES [TYPE](ID)
);

CREATE TABLE VENDOR (
    TIN VARCHAR(20) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Address_detail NVARCHAR(255) NOT NULL,
    Contact_Info VARCHAR(255),
    Longitude DECIMAL(9, 6) CHECK (Longitude BETWEEN -180 AND 180),
    Latitude DECIMAL(9, 6) CHECK (Latitude BETWEEN -90 AND 90),
    P_ID INT,
    FOREIGN KEY (P_ID) REFERENCES PROVINCE(ID)
);

-- PDF Bảng 15: CarrierCompany kế thừa từ Vendor, không có cột Name/Address riêng
CREATE TABLE CARRIERCOMPANY (
    V_TIN VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (V_TIN) REFERENCES VENDOR(TIN)
);

CREATE TABLE DISTRIBUTOR (
    Vendor_TIN VARCHAR(20) PRIMARY KEY,
    Type VARCHAR(50) NOT NULL CHECK (Type IN ('Direct', 'Indirect')),
    FOREIGN KEY (Vendor_TIN) REFERENCES VENDOR(TIN) ON DELETE CASCADE
);

CREATE TABLE RETAIL (
    Vendor_TIN VARCHAR(20) PRIMARY KEY,
    Format NVARCHAR(100) NOT NULL CHECK (Format IN (N'Supermarket', N'Online Store', N'Convenience Store', N'Traditional Market', N'Specialty Shop')),
    FOREIGN KEY (Vendor_TIN) REFERENCES VENDOR(TIN) ON DELETE CASCADE
);


CREATE TABLE VENDOR_PRODUCT (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    AP_ID INT NOT NULL,
    Vendor_TIN VARCHAR(20) NOT NULL,
    Unit NVARCHAR(50) NOT NULL, -- Ví dụ: kg, tấn, hộp
    ValuePerUnit DECIMAL(10, 2), -- Giá gốc mỗi đơn vị
    FOREIGN KEY (Vendor_TIN) REFERENCES VENDOR(TIN),
    FOREIGN KEY (AP_ID) REFERENCES AGRICULTURE_PRODUCT(ID),
);

CREATE TABLE BATCH (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Harvest_Date DATETIMEOFFSET NOT NULL,
    Created_By NVARCHAR(100),
    Grade VARCHAR(50),
    Seed_Batch VARCHAR(100),
    Qr_Code_URL VARCHAR(2048) NOT NULL UNIQUE,
    Farm_ID INT NOT NULL,
    AP_ID INT NOT NULL,
    V_ID INT,
    FOREIGN KEY (Farm_ID) REFERENCES FARM(ID),
    FOREIGN KEY (AP_ID) REFERENCES AGRICULTURE_PRODUCT(ID),
    FOREIGN KEY (V_ID) REFERENCES VENDOR_PRODUCT(ID)
);

CREATE TABLE PROCESSING (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Packaging_Date DATETIMEOFFSET NOT NULL,
    Weight_per_unit DECIMAL(10, 2) NOT NULL CHECK (Weight_per_unit > 0),
    Processed_By NVARCHAR(100),
    Packaging_Type NVARCHAR(100),
    Processing_Date DATETIMEOFFSET,
    Facility_ID INT NOT NULL,
    Batch_ID INT NOT NULL,
    FOREIGN KEY (Facility_ID) REFERENCES PROCESSING_FACILITY(ID),
    FOREIGN KEY (Batch_ID) REFERENCES BATCH(ID),
    CHECK (Packaging_Date > Processing_Date)
);

-- Process Step phụ thuộc vào PROCESSING (các bước của một lần chế biến)
CREATE TABLE PROCESS_STEP (
    P_ID INT NOT NULL,
    Step NVARCHAR(255) NOT NULL,
    PRIMARY KEY (P_ID, Step),
    FOREIGN KEY (P_ID) REFERENCES PROCESSING(ID) ON DELETE CASCADE
);

CREATE TABLE SHIPMENT (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Status VARCHAR(50) NOT NULL CHECK (Status IN ('Pending', 'In-Transit', 'Delivered', 'Cancelled')),
    Destination NVARCHAR(255),
    Start_Location NVARCHAR(255),
    Distributor_TIN VARCHAR(20) NOT NULL,
    FOREIGN KEY (Distributor_TIN) REFERENCES DISTRIBUTOR(Vendor_TIN)
);

CREATE TABLE TRANSPORLEG (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Shipment_ID INT NOT NULL,
    Driver_Name NVARCHAR(100),
    Temperature_Profile NVARCHAR(MAX),
    Start_Location NVARCHAR(255) NOT NULL,
    To_Location NVARCHAR(255) NOT NULL,
    D_Time DATETIMEOFFSET,
    A_Time DATETIMEOFFSET,
    CarrierCompany_TIN VARCHAR(20) NOT NULL,
    FOREIGN KEY (Shipment_ID) REFERENCES SHIPMENT(ID),
    FOREIGN KEY (CarrierCompany_TIN) REFERENCES CARRIERCOMPANY(V_TIN),
    CHECK (A_Time > D_Time)
);

CREATE TABLE SHIP_BATCH (
    S_ID INT NOT NULL,
    B_ID INT NOT NULL,
    PRIMARY KEY (S_ID, B_ID),
    FOREIGN KEY (S_ID) REFERENCES SHIPMENT(ID),
    FOREIGN KEY (B_ID) REFERENCES BATCH(ID)
);

CREATE TABLE STORED_IN (
    B_ID INT NOT NULL,
    W_ID INT NOT NULL,
    Quantity DECIMAL(10, 2) NOT NULL CHECK (Quantity >= 0),
    Start_Date DATETIMEOFFSET,
    End_Date DATETIMEOFFSET,
    PRIMARY KEY (B_ID, W_ID),
    FOREIGN KEY (B_ID) REFERENCES BATCH(ID),
    FOREIGN KEY (W_ID) REFERENCES WAREHOUSE(ID),
    CHECK (End_Date > Start_Date)
);

CREATE TABLE PRICE (
    V_ID INT PRIMARY KEY,
    Value DECIMAL(12, 2) NOT NULL CHECK (Value > 0),
    Currency VARCHAR(3) NOT NULL DEFAULT 'VND',
    FOREIGN KEY (V_ID) REFERENCES VENDOR_PRODUCT(ID) ON DELETE CASCADE
);

CREATE TABLE DISCOUNT (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255),
    Percentage DECIMAL(5, 2) CHECK (Percentage > 0 AND Percentage <= 100),
    Min_Value DECIMAL(12, 2),       
    Max_Discount_Amount DECIMAL(12, 2), 
    Priority INT DEFAULT 0,          
    Is_Stackable BIT DEFAULT 0,      
    Start_Date DATETIMEOFFSET NOT NULL,
    Expired_Date DATETIMEOFFSET NOT NULL,
    CHECK (Expired_Date > Start_Date)
);

CREATE TABLE PRODUCT_HAS_DISCOUNT (
    V_ID INT NOT NULL,
    Discount_ID INT NOT NULL,
    PRIMARY KEY (V_ID, Discount_ID),
    FOREIGN KEY (V_ID) REFERENCES VENDOR_PRODUCT(ID),
    FOREIGN KEY (Discount_ID) REFERENCES DISCOUNT(ID)
);